name: dson_core
version: 0.12.0
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson_core
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  source_gen: ^0.7.0
  build: ^0.12.0
  analyzer: ^0.31.0
  logging: ^0.11.0
  built_mirrors_core: ^0.8.2
  serializable_core: ^0.8.1
#  serializable_core:
#    path: ../serializable
#  built_mirrors_core:
#    path: ../built_mirrors
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
