name: dson_core
version: 0.15.6
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson_core
environment:
  sdk: '>=1.8.0 <3.0.0'
dependencies:
  source_gen: ^0.9.0
  build: ^1.0.1
  analyzer: ^0.36.0
  logging: ^0.11.0
  serializable_core: ^0.11.2+1
#  serializable_core:
#    path: ../serializable_core
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
